name: Node.js CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: cd SBOM-Catalog && npm install

      - name: Run build
        run: cd SBOM-Catalog && npm run build

      - name: Syft SPDX SBOM generation
        uses: anchore/sbom-action@v0
        with:
          artifact-name: sbom-spdx
          format: spdx-json

      - name: Syft CycloneDx SBOM generation
        uses: anchore/sbom-action@v0
        with:
          artifact-name: sbom-cyclonedx
          format: cylconedx-json

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: SBOM-Catalog/dist
          branch: gh-pages

