name: CI

on:
  pull_request:

  workflow_dispatch:

jobs:
  build-catalog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r .github/requirements.txt

      - name: Lint Catalog Data
        run: yamllint -d relaxed SBOM-Catalog

      - name: Schema Check Catalog Data
        run: yamale -s SBOM-Catalog/schemas/data.yaml SBOM-Catalog/public/data.yaml

      - name: Schema Check Catalog Filters
        run: yamale -s SBOM-Catalog/schemas/filters.yaml SBOM-Catalog/public/filters.yaml

      - name: Install dependencies
        run: cd SBOM-Catalog && npm install

      - name: Run lint
        run: cd SBOM-Catalog && npm run lint

      - name: Run Unit-Tests
        run: cd SBOM-Catalog && npm run test

      - name: Run build
        run: cd SBOM-Catalog && npm run build


  build-wiki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: cd SBOM-wiki && npm install

      - name: Run build
        run: cd SBOM-wiki && npm run build
